services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    env_file: .env
    security_opt:
      - no-new-privileges:true
    networks:
      proxynet:
        ipv4_address: 172.18.0.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`dash.example.tld`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
networks:
  proxynet:
    external: true

secrets:
  cf_dns_api_token:
    file: ./secrets/cf_dns_api_token